// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* CrearAlumno.h
   Generated by wsdl2h 2.8.36 from http://localhost/CrearAlumno.wsdl and typemap.dat
   2016-11-06 07:03:38 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on CrearAlumno.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stl.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   urn:CrearAlumno                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER                                                                 *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/

template <class T> class std::vector;

/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/

#import "stl.h"	// enable STL containers when used (option -s removes STL dependency)

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "urn:CrearAlumno"

*/

#define SOAP_NAMESPACE_OF_ns1	"urn:CrearAlumno"
//gsoap ns1   schema namespace:	urn:CrearAlumno
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class ns1__Input.
class ns1__Input;

//  Forward declaration of class ns1__getInfoResponse.
class ns1__getInfoResponse;

//  Forward declaration of class _ns1__getInfo.
class _ns1__getInfo;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   urn:CrearAlumno                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   urn:CrearAlumno                                                          *
 *                                                                            *
\******************************************************************************/

/// @brief "urn:CrearAlumno":Input is a complexType.
///
/// class ns1__Input operations:
/// - ns1__Input* soap_new_ns1__Input(soap*) allocate and default initialize
/// - ns1__Input* soap_new_ns1__Input(soap*, int num) allocate array and default initialize values
/// - ns1__Input* soap_new_req_ns1__Input(soap*, ...) allocate, set required members
/// - ns1__Input* soap_new_set_ns1__Input(soap*, ...) allocate, set all public members
/// - ns1__Input::soap_default(soap*) default initialize members
/// - int soap_read_ns1__Input(soap*, ns1__Input*) deserialize from a stream
/// - int soap_write_ns1__Input(soap*, ns1__Input*) serialize to a stream
/// - ns1__Input* ns1__Input::soap_dup(soap*) returns deep copy of ns1__Input, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns1__Input::soap_del() deep deletes ns1__Input data members, use only after ns1__Input::soap_dup(NULL) (use soapcpp2 -Ed)
class ns1__Input
{ public:
/// Element "nombre" of XSD type xs:string.
    std::string*                         nombre                         0;	///< Optional element.
/// A handle to the soap struct context that manages this instance when instantiated by a context or NULL otherwise (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "urn:CrearAlumno":getInfoResponse is a complexType.
///
/// class ns1__getInfoResponse operations:
/// - ns1__getInfoResponse* soap_new_ns1__getInfoResponse(soap*) allocate and default initialize
/// - ns1__getInfoResponse* soap_new_ns1__getInfoResponse(soap*, int num) allocate array and default initialize values
/// - ns1__getInfoResponse* soap_new_req_ns1__getInfoResponse(soap*, ...) allocate, set required members
/// - ns1__getInfoResponse* soap_new_set_ns1__getInfoResponse(soap*, ...) allocate, set all public members
/// - ns1__getInfoResponse::soap_default(soap*) default initialize members
/// - int soap_read_ns1__getInfoResponse(soap*, ns1__getInfoResponse*) deserialize from a stream
/// - int soap_write_ns1__getInfoResponse(soap*, ns1__getInfoResponse*) serialize to a stream
/// - ns1__getInfoResponse* ns1__getInfoResponse::soap_dup(soap*) returns deep copy of ns1__getInfoResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns1__getInfoResponse::soap_del() deep deletes ns1__getInfoResponse data members, use only after ns1__getInfoResponse::soap_dup(NULL) (use soapcpp2 -Ed)
class ns1__getInfoResponse
{ public:
/// Element "recepcion" of XSD type xs:string.
    std::string*                         recepcion                      0;	///< Optional element.
/// A handle to the soap struct context that manages this instance when instantiated by a context or NULL otherwise (automatically set).
    struct soap                         *soap                          ;
};

/// @brief Top-level root element "urn:CrearAlumno":getInfo
/// @brief "urn:CrearAlumno":getInfo is a complexType.
///
/// class _ns1__getInfo operations:
/// - _ns1__getInfo* soap_new__ns1__getInfo(soap*) allocate and default initialize
/// - _ns1__getInfo* soap_new__ns1__getInfo(soap*, int num) allocate array and default initialize values
/// - _ns1__getInfo* soap_new_req__ns1__getInfo(soap*, ...) allocate, set required members
/// - _ns1__getInfo* soap_new_set__ns1__getInfo(soap*, ...) allocate, set all public members
/// - _ns1__getInfo::soap_default(soap*) default initialize members
/// - int soap_read__ns1__getInfo(soap*, _ns1__getInfo*) deserialize from a stream
/// - int soap_write__ns1__getInfo(soap*, _ns1__getInfo*) serialize to a stream
/// - _ns1__getInfo* _ns1__getInfo::soap_dup(soap*) returns deep copy of _ns1__getInfo, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - _ns1__getInfo::soap_del() deep deletes _ns1__getInfo data members, use only after _ns1__getInfo::soap_dup(NULL) (use soapcpp2 -Ed)
class _ns1__getInfo
{ public:
/// Element "insert" of XSD type "urn:CrearAlumno":Input.
    ns1__Input*                          insert                         0;	///< Optional element.
/// A handle to the soap struct context that manages this instance when instantiated by a context or NULL otherwise (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   urn:CrearAlumno                                                          *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "urn:CrearAlumno":getInfoResponse of XSD type "urn:CrearAlumno":getInfoResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   urn:CrearAlumno                                                          *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	CrearAlumno 
//gsoap ns1  service type:	CrearAlumnoPortType 
//gsoap ns1  service port:	http://localhost/cgi-bin/CrearAlumno.cgi 
//gsoap ns1  service namespace:	urn:CrearAlumno 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage CrearAlumno Definitions

@section CrearAlumno_bindings Service Bindings

  - @ref CrearAlumno

@section CrearAlumno_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page CrearAlumno Binding "CrearAlumno"

@section CrearAlumno_service Service Documentation "CrearAlumno"
gSOAP 2.8.36 generated service definition

@section CrearAlumno_operations Operations of Binding "CrearAlumno"

  - @ref __ns1__getInfo

@section CrearAlumno_ports Default endpoints of Binding "CrearAlumno"

  - http://localhost/cgi-bin/CrearAlumno.cgi

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   CrearAlumno                                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getInfo                                                           *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getInfo" of service binding "CrearAlumno".
Service definition of function ns__getInfo

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://localhost/cgi-bin/CrearAlumno.cgi

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getInfo(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__getInfo*                      ns1__getInfo,
    // output parameters:
    ns1__getInfoResponse               &ns1__getInfoResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getInfo(
    struct soap *soap,
    // input parameters:
    _ns1__getInfo*                      ns1__getInfo,
    // output parameters:
    ns1__getInfoResponse               &ns1__getInfoResponse_
  );
@endcode

C++ proxy class (defined in soapCrearAlumnoProxy.h generated with soapcpp2):
@code
  class CrearAlumnoProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapCrearAlumnoService.h generated with soapcpp2):
@code
  class CrearAlumnoService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getInfo SOAP
//gsoap ns1  service method-style:	getInfo document
//gsoap ns1  service method-encoding:	getInfo literal
//gsoap ns1  service method-action:	getInfo ""
//gsoap ns1  service method-output-action:	getInfo Response
int __ns1__getInfo(
    _ns1__getInfo*                      ns1__getInfo,	///< Input parameter
    ns1__getInfoResponse               &ns1__getInfoResponse_	///< Output parameter
);

/**

@page CrearAlumno Binding "CrearAlumno"

@section CrearAlumno_policy_enablers Policy Enablers of Binding "CrearAlumno"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns1 Top-level root elements of schema "urn:CrearAlumno"

  - <ns1:getInfo> @ref _ns1__getInfo
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__getInfo(struct soap*, _ns1__getInfo*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__getInfo(struct soap*, _ns1__getInfo*);
    @endcode

  - <ns1:getInfoResponse> (use wsdl2h option -g to auto-generate type _ns1__getInfoResponse)

*/

/* End of CrearAlumno.h */
