/* soapServer.cpp
   Generated by gSOAP 2.8.36 for RegistryOperations.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.36 2016-11-11 04:53:23 GMT")
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if ((soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap))) && soap->error && soap->error < SOAP_STOP)
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:InsertUser"))
		return soap_serve_ns__InsertUser(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:GetUser"))
		return soap_serve_ns__GetUser(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__InsertUser(struct soap *soap)
{	struct ns__InsertUser soap_tmp_ns__InsertUser;
	struct ns__InsertUserResponse soap_tmp_ns__InsertUserResponse;
	char soap_tmp_byte;
	soap_default_ns__InsertUserResponse(soap, &soap_tmp_ns__InsertUserResponse);
	soap_default_byte(soap, &soap_tmp_byte);
	soap_tmp_ns__InsertUserResponse.result_soap = &soap_tmp_byte;
	soap_default_ns__InsertUser(soap, &soap_tmp_ns__InsertUser);
	if (!soap_get_ns__InsertUser(soap, &soap_tmp_ns__InsertUser, "ns:InsertUser", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__InsertUser(soap, soap_tmp_ns__InsertUser.userIn, soap_tmp_ns__InsertUserResponse.result_soap);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns__InsertUserResponse(soap, &soap_tmp_ns__InsertUserResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__InsertUserResponse(soap, &soap_tmp_ns__InsertUserResponse, "ns:InsertUserResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__InsertUserResponse(soap, &soap_tmp_ns__InsertUserResponse, "ns:InsertUserResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__GetUser(struct soap *soap)
{	struct ns__GetUser soap_tmp_ns__GetUser;
	struct ns__GetUserResponse soap_tmp_ns__GetUserResponse;
	char soap_tmp_byte;
	soap_default_ns__GetUserResponse(soap, &soap_tmp_ns__GetUserResponse);
	soap_default_byte(soap, &soap_tmp_byte);
	soap_tmp_ns__GetUserResponse.result_soap = &soap_tmp_byte;
	soap_default_ns__GetUser(soap, &soap_tmp_ns__GetUser);
	if (!soap_get_ns__GetUser(soap, &soap_tmp_ns__GetUser, "ns:GetUser", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__GetUser(soap, soap_tmp_ns__GetUser.user, soap_tmp_ns__GetUser.pass, soap_tmp_ns__GetUser.userGet, soap_tmp_ns__GetUserResponse.result_soap);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_ns__GetUserResponse(soap, &soap_tmp_ns__GetUserResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetUserResponse(soap, &soap_tmp_ns__GetUserResponse, "ns:GetUserResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetUserResponse(soap, &soap_tmp_ns__GetUserResponse, "ns:GetUserResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
